FROM ruby:2.5.5-alpine
WORKDIR /app
COPY . /app
RUN bundle install
# Install Yarn.
RUN apk add yarn

# Set "rails server -b 0.0.0.0" as the command to
# run when this container starts.
CMD ["rails", "server", "-b", "0.0.0.0"]
